services:
  app:
    build: .
    container_name: url-shortener
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=url_shortener
      - DOMAIN=localhost:3000
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: url_shortener
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:

