@url = http://localhost:3000
@contenttype = application/json

###

GET {{url}}/ping

###

GET {{url}}/abc

###

POST {{url}}/api/v1
Content-Type: {{contenttype}}

{
   "url": "http://example.com",
   "short": "abc",
   "expiry": 24
}

###

GET {{url}}/api/v1/analytics/abc
Content-Type: {{contenttype}}