@url = http://localhost:3000
@contenttype = application/json
@authorization = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDIwNjI0NjEsImlhdCI6MTc0MjA1ODg2MSwiaXNzIjoidXJsX3Nob3J0ZW5lciIsInVzZXJuYW1lIjoiYW1pciJ9.51bh83eKW6hVHqEAFwls8Gbg5FscNDrP4dIjbElpaMcc5TA-qMp0da3EWiZw2Z5U3RSuQov9tAdyPZALlvj0tw
### Test URL
GET {{url}}/ping

### Redirect
GET {{url}}/0FL0EApfD

### Short URL create
POST {{url}}/api/v1
Content-Type: {{contenttype}}
Authorization: {{authorization}}

{
   "url": "http://google.com",
   "expiry": 24
}

### Get analytics
GET {{url}}/api/v1/analytics/imq0q9xps
Content-Type: {{contenttype}}

### Get urls
GET {{url}}/api/v1/urls
Authorization: {{authorization}}
Content-Type: {{contenttype}}


### Users register
POST {{url}}/api/v1/register
Content-Type: {{contenttype}}

{
   "username": "amir",
   "password": "Qwerty"
}


### Users login
POST {{url}}/api/v1/login
Content-Type: {{contenttype}}

{
   "username": "amir",
   "password": "Qwerty"
}
